### PR TITLE
Lookup: expandable layouted cards

### PR DESCRIPTION
**Pull request by jude7733**
**TODO:** 
- [ ] implement sort
- [ ] fix alignment/showing content 
- [ ]  find suitable Heading

@Abhiram-P-Ashok tell ui of cards
@Stalinosmj or @JeffinPappachan veneel implement sorting or I'll (first sort from Lookup based on options and give to lookup-cards)

### CODE REVIEW

**Comment by jude7733** [comment]
BUG: animation poi in production build huff

**Review by Stalinosmj — COMMENTED** [review]
Vethyasam onnum kaanunilala

**Comment by Stalinosmj** [comment]
> Vethyasam onnum kaanunilala

Oh phnil vethyasam illathe

**Comment by jude7733** [comment]
Nee development serveril run cheyth nok. Animation varum

**Comment by jude7733** [comment]
@Stalinosmj check now

**Comment by Stalinosmj** [comment]
Phnil ippoyum layout okke shogam but nannayitund 🙂

**Comment by jude7733** [comment]
Fixing postponed (lookup usecase aadyam ila)

**Pull request merged**
