### PR TITLE
changed dashboard

### PR DESCRIPTION
**Pull request by Stalinosmj**

### CODE REVIEW

**Comment by Stalinosmj** [comment]
@jude7733 need to fix buttons in wobble card

**Review by jude7733 — COMMENTED** [review]
**Progress?**

**Comment by Stalinosmj** [comment]
Aavo njn aa button sheriyakan nokate

**Review by jude7733 — COMMENTED** [review]
Hmm

**Comment by Stalinosmj** [comment]
dei aa conflict kalanje
auth page nee aan uncharge

**Comment by Stalinosmj** [comment]
valathum nadako

**Comment by jude7733** [comment]
> valathum nadako

ayne thodangilala

**Comment by jude7733** [comment]
Da @Stalinosmj  , @Abhiram-P-Ashok review chyathath kondana, can't merge(dim aayi kidakaneya), and y delete aa file

**Pull request closed without merging**
