### PR TITLE
UI rework

### PR DESCRIPTION
**Pull request by Stalinosmj**
@jude7733 

- [ ] 1. sidebar nadanila so njn thane orenm indaki 
- [ ] 2. pinne manasilayi layout file maari poyi
- [ ] 3. tabs full content load aakanila

 **ithoke nalle cheynm**

### CODE REVIEW

**Comment by Stalinosmj** [comment]
> @jude7733
> 
> * [ ]  1. sidebar nadanila so njn thane orenm indaki
> * [ ]  2. pinne manasilayi layout file maari poyi
> * [ ]  3. tabs full content load aakanila
> 
> **ithoke nalle cheynm**

layout file maari poya kond dashboard page nere open aayila

**Review by jude7733 — COMMENTED** [review]
Breadcrumbs navbar elam kalanja

**Comment by jude7733** [comment]
**progress?**

**Comment by Stalinosmj** [comment]
> **progress?**

Current ⚡ illa, veedinte frontil maram 🌲 veen

**Pull request closed without merging**
