### PR TITLE
Login page animated tabs

### PR DESCRIPTION
**Pull request by jude7733**
Need  to fix colors @Abhiram-P-Ashok

### CODE REVIEW

**Review by Stalinosmj — APPROVED** [review]
🙈🙉🙊

**Comment by jude7733** [comment]
@Stalinosmj where do we keep icons?

**Comment by Stalinosmj** [comment]
> @Stalinosmj where do we keep icons?

Eth iconsphere aana , ath hide aak in mobile

**Comment by jude7733** [comment]
> > @Stalinosmj where do we keep icons?
> 
> Eth iconsphere aana , ath hide aak in mobile

icon sphere irikate in phone, whats the prob? nyan udeshichath mate nee itta svg  /components/icons/*

**Comment by Stalinosmj** [comment]
> > > @Stalinosmj where do we keep icons?
> > 
> > 
> > Eth iconsphere aana , ath hide aak in mobile
> 
> icon sphere irikate in phone, whats the prob? nyan udeshichath mate nee itta svg /components/icons/*

ath eduth kala 
phnil auth page ithuvere scroll cheyth kandatila atha njn venda enn paranje, designil oru apakatha pole @Abhiram-P-Ashok ui designer ennthenkilum parayada kope

**Comment by jude7733** [comment]
@Abhiram-P-Ashok or @JeffinPappachan or @angeloseby ... login pageil icon-cloud veno (in phone)??

**Comment by Stalinosmj** [comment]
Kya kar rahe ho bhai

**Comment by jude7733** [comment]
Matte preview set aakan nokan.. pushing, force delete, ...pushing force delete becz failing

**Pull request merged**
