### PR TITLE
Jude7733/main

### PR DESCRIPTION
**Pull request by Stalinosmj**

### CODE REVIEW

**Review by jude7733 — COMMENTED** [review]
huh Y hide icon cloud in phone,, and y open another pull req from my pull req, onnum manasilakanila.. 
and Dept name ale pokath varande, and footeril ale teconiq-dev varande according to @angeloseby

**Comment by Stalinosmj** [comment]
> huh Y hide icon cloud in phone,, and y open another pull req from my pull req, onnum manasilakanila.. and Dept name ale pokath varande, and footeril ale teconiq-dev varande according to @angeloseby

dept name boring
and why new pr idk njn checkout aan cheythe but ath kayin commit cheythapo new pr aayi(idk how to use checkout)
icon cloud phnil enthina kanikane

**Comment by Stalinosmj** [comment]
> > huh Y hide icon cloud in phone,, and y open another pull req from my pull req, onnum manasilakanila.. and Dept name ale pokath varande, and footeril ale teconiq-dev varande according to @angeloseby
> 
> dept name boring and why new pr idk njn checkout aan cheythe but ath kayin commit cheythapo new pr aayi(idk how to use checkout) icon cloud phnil enthina kanikane

nee oru git cls eduth thaaa ;)

**Comment by jude7733** [comment]
Ipo delete akandarn

**Pull request closed without merging**
